name: xiaomi-nabu
run-name: Xiaomi Pad 5
on:
  push:
    paths:
      - 'devices/xiaomi-nabu/**'
      - '.github/workflows/xiaomi-nabu.yml'
      - '.github/workflows/xiaomi-nabu-esp-repacker.yml'

jobs:
  repack-run:
    uses: ./.github/workflows/xiaomi-nabu-esp-repacker.yml
    with:
      release_url: https://github.com/pocketblue/pocketblue/releases/download/43.20251220/pocketblue-xiaomi-nabu-gnome-desktop-43.7z
